// DO NOT EDIT. This file is generated by fresh.
// This file SHOULD be checked into source version control.
// This file is automatically updated during development when running `dev.ts`.

import config from "./deno.json" assert { type: "json" };
import * as $0 from "./routes/[blog]/this.tsx";
import * as $1 from "./routes/[toys]/index.tsx";
import * as $2 from "./routes/[toys]/spinners.tsx";
import * as $3 from "./routes/api/joke.ts";
import * as $4 from "./routes/index.tsx";
import * as $$0 from "./islands/BlogNavigationButtons.tsx";
import * as $$1 from "./islands/InsanitySection.tsx";
import * as $$2 from "./islands/StyledButton.tsx";
import * as $$3 from "./islands/ThemeSwitcher.tsx";

const manifest = {
  routes: {
    "./routes/[blog]/this.tsx": $0,
    "./routes/[toys]/index.tsx": $1,
    "./routes/[toys]/spinners.tsx": $2,
    "./routes/api/joke.ts": $3,
    "./routes/index.tsx": $4,
  },
  islands: {
    "./islands/BlogNavigationButtons.tsx": $$0,
    "./islands/InsanitySection.tsx": $$1,
    "./islands/StyledButton.tsx": $$2,
    "./islands/ThemeSwitcher.tsx": $$3,
  },
  baseUrl: import.meta.url,
  config,
};

export default manifest;
