// DO NOT EDIT. This file is generated by fresh.
// This file SHOULD be checked into source version control.
// This file is automatically updated during development when running `dev.ts`.

import * as $0 from "./routes/_404.tsx";
import * as $1 from "./routes/_500.tsx";
import * as $2 from "./routes/blog/experience-deno-fresh.tsx";
import * as $3 from "./routes/blog/how-create-categories-discord-v14.tsx";
import * as $4 from "./routes/blog/how-create-roles-discord-v14.tsx";
import * as $5 from "./routes/blog/how-create-text-channels-discord-v14.tsx";
import * as $6 from "./routes/blog/how-create-theme-switcher-deno-fresh.tsx";
import * as $7 from "./routes/blog/how-create-voice-channels-discord-v14.tsx";
import * as $8 from "./routes/blog/index.tsx";
import * as $9 from "./routes/blog/javascript-python-syntax.tsx";
import * as $10 from "./routes/blog/stopping-theme-flickering-deno-fresh.tsx";
import * as $11 from "./routes/certificates.tsx";
import * as $12 from "./routes/index.tsx";
import * as $13 from "./routes/me.tsx";
import * as $14 from "./routes/projects/expenses-tracker.tsx";
import * as $15 from "./routes/projects/food-order/checkout.tsx";
import * as $16 from "./routes/projects/food-order/index.tsx";
import * as $17 from "./routes/projects/food-order/success.tsx";
import * as $18 from "./routes/projects/index.tsx";
import * as $19 from "./routes/projects/stimulus-check.tsx";
import * as $20 from "./routes/projects/tictactoe.tsx";
import * as $21 from "./routes/tools/expression-visualizer.tsx";
import * as $22 from "./routes/tools/highlighted-text/[text].tsx";
import * as $23 from "./routes/tools/index.tsx";
import * as $24 from "./routes/tools/retirement-calculator.tsx";
import * as $25 from "./routes/tools/syntax-highlight.tsx";
import * as $26 from "./routes/tools/whatsapp-message-link-generator.tsx";
import * as $27 from "./routes/toys/index.tsx";
import * as $28 from "./routes/toys/insanity.tsx";
import * as $29 from "./routes/toys/spinners.tsx";
import * as $30 from "./routes/what-is-this.tsx";
import * as $31 from "./routes/work/index.tsx";
import * as $$0 from "./islands/UI/DigitalTimer.tsx";
import * as $$1 from "./islands/UI/Modal.tsx";
import * as $$2 from "./islands/misc/Collapsible.tsx";
import * as $$3 from "./islands/misc/CopyTextAreaToClipboard.tsx";
import * as $$4 from "./islands/misc/ScrollToTop.tsx";
import * as $$5 from "./islands/misc/ThemeSwitcher.tsx";
import * as $$6 from "./islands/projects/AddNewExpense.tsx";
import * as $$7 from "./islands/projects/ExpensesTracker.tsx";
import * as $$8 from "./islands/projects/ExpensesYearSelect.tsx";
import * as $$9 from "./islands/projects/FoodOrder.tsx";
import * as $$10 from "./islands/projects/FoodOrderCheckout.tsx";
import * as $$11 from "./islands/projects/FormWithValidation.tsx";
import * as $$12 from "./islands/projects/TicTacToeBoard.tsx";
import * as $$13 from "./islands/tools/ExpressionVisualizationList.tsx";
import * as $$14 from "./islands/tools/ExpressionVisualizer.tsx";
import * as $$15 from "./islands/tools/HighlightedCode.tsx";
import * as $$16 from "./islands/tools/RetirementCalculationForm.tsx";
import * as $$17 from "./islands/tools/RetirementCalculator.tsx";
import * as $$18 from "./islands/tools/WhatsappLinkGenerator.tsx";
import * as $$19 from "./islands/toys/InsanitySection.tsx";

const manifest = {
  routes: {
    "./routes/_404.tsx": $0,
    "./routes/_500.tsx": $1,
    "./routes/blog/experience-deno-fresh.tsx": $2,
    "./routes/blog/how-create-categories-discord-v14.tsx": $3,
    "./routes/blog/how-create-roles-discord-v14.tsx": $4,
    "./routes/blog/how-create-text-channels-discord-v14.tsx": $5,
    "./routes/blog/how-create-theme-switcher-deno-fresh.tsx": $6,
    "./routes/blog/how-create-voice-channels-discord-v14.tsx": $7,
    "./routes/blog/index.tsx": $8,
    "./routes/blog/javascript-python-syntax.tsx": $9,
    "./routes/blog/stopping-theme-flickering-deno-fresh.tsx": $10,
    "./routes/certificates.tsx": $11,
    "./routes/index.tsx": $12,
    "./routes/me.tsx": $13,
    "./routes/projects/expenses-tracker.tsx": $14,
    "./routes/projects/food-order/checkout.tsx": $15,
    "./routes/projects/food-order/index.tsx": $16,
    "./routes/projects/food-order/success.tsx": $17,
    "./routes/projects/index.tsx": $18,
    "./routes/projects/stimulus-check.tsx": $19,
    "./routes/projects/tictactoe.tsx": $20,
    "./routes/tools/expression-visualizer.tsx": $21,
    "./routes/tools/highlighted-text/[text].tsx": $22,
    "./routes/tools/index.tsx": $23,
    "./routes/tools/retirement-calculator.tsx": $24,
    "./routes/tools/syntax-highlight.tsx": $25,
    "./routes/tools/whatsapp-message-link-generator.tsx": $26,
    "./routes/toys/index.tsx": $27,
    "./routes/toys/insanity.tsx": $28,
    "./routes/toys/spinners.tsx": $29,
    "./routes/what-is-this.tsx": $30,
    "./routes/work/index.tsx": $31,
  },
  islands: {
    "./islands/UI/DigitalTimer.tsx": $$0,
    "./islands/UI/Modal.tsx": $$1,
    "./islands/misc/Collapsible.tsx": $$2,
    "./islands/misc/CopyTextAreaToClipboard.tsx": $$3,
    "./islands/misc/ScrollToTop.tsx": $$4,
    "./islands/misc/ThemeSwitcher.tsx": $$5,
    "./islands/projects/AddNewExpense.tsx": $$6,
    "./islands/projects/ExpensesTracker.tsx": $$7,
    "./islands/projects/ExpensesYearSelect.tsx": $$8,
    "./islands/projects/FoodOrder.tsx": $$9,
    "./islands/projects/FoodOrderCheckout.tsx": $$10,
    "./islands/projects/FormWithValidation.tsx": $$11,
    "./islands/projects/TicTacToeBoard.tsx": $$12,
    "./islands/tools/ExpressionVisualizationList.tsx": $$13,
    "./islands/tools/ExpressionVisualizer.tsx": $$14,
    "./islands/tools/HighlightedCode.tsx": $$15,
    "./islands/tools/RetirementCalculationForm.tsx": $$16,
    "./islands/tools/RetirementCalculator.tsx": $$17,
    "./islands/tools/WhatsappLinkGenerator.tsx": $$18,
    "./islands/toys/InsanitySection.tsx": $$19,
  },
  baseUrl: import.meta.url,
};

export default manifest;
